name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    #dekho
    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID
